### ISSUE TITLE
Table missing from List of All Config Variables

### ISSUE THREAD

**Issue by Moguri** [Moguri/panda-sphinx#3]
https://moguri.github.io/panda-sphinx/programming-with-panda3d/the-configuration-file/list-of-all-config-variables.html

**Comment by tcdude** [comment]
Also, this line should be updated `The following is an incomplete list of config variables as of Jun, 2009.` with a more current date

**Comment by rdb** [comment]
We can probably automatically generate a new table in whatever format we want to do in Sphinx.
